name = "app"
main = "src/index.ts"
compatibility_date = "2024-12-14"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
GEMINI_API= "your gemini api key"
DATABASE_URL="your connection pool url"

# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1